import { SupportedChainId } from "@/types/network/supportedNetwork";
import {
  MAINNET_CONTRACTS,
  SEPOLIA_CONTRACTS,
  THANOS_SEPOLIA_CONTRACTS,
  TITAN_SEPOLIA_CONTRACTS,
  TOKAMAK_CONTRACTS,
} from ".";

export const WETH_ADDRESS_BY_CHAINID: Record<number, string> = {
  [SupportedChainId.MAINNET]: MAINNET_CONTRACTS.WETH_ADDRESS,
  [SupportedChainId.SEPOLIA]: SEPOLIA_CONTRACTS.WETH_ADDRESS,
  [SupportedChainId.TITAN]: TOKAMAK_CONTRACTS.WETH_ADDRESS,
  [SupportedChainId.TITAN_SEPOLIA]: TITAN_SEPOLIA_CONTRACTS.WETH_ADDRESS,
};
