name: Report any bugs
description: Rewards may be available based on the bug impact
title: "[Bugs]: "
labels: [bug]
assignees:
  - suahnkim,SonYoungsung,monica-tokamak,zzooppii,black02430horse
body:
  - type: markdown
    attributes:
      value: |
        Rewards may be available based on the bug impact. 
  - type: dropdown
    id: feature
    attributes:
      label: Can you specify where the bug exists?
      multiple: true
      options:
        - swap
        - deposit
        - withdraw
        - Uniswapv3 pools (add, remove, collect)
        - Cross Trade
        - Others
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? 
      placeholder: Tell us what you see! 
      value: "Describe the bug and its behavior! You can also upload the image and code links"
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: Which networks are you seeing the problem on? (can select multiple)
      multiple: true
      options:
        - Ethereum
        - Titan
        - Thanos
        - Sepolia testnet 
        - Titan Sepolia testnet
        - Thanos Sepolia testnet
  - type: dropdown
    id: Device
    attributes:
      label: Which device are you seeing the problem on? (can select multiple)
      multiple: true
      options:
        - Desktop
        - Tablet
        - Mobile
        - Others
  - type: dropdown
    id: OS
    attributes:
      label: Which OS are you seeing the problem on? (can select multiple)
      multiple: true
      options:
        - Windows
        - Android
        - MacOS
        - iOS
        - Others
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on? (can select multiple)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Others
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-output
    attributes:
      label: Upload any screenshots to aid with explaining the bug.
      description: Upload screenshots
      placeholder:  Tell us what you see!
      value: "Upload image here"
    validations:
      required: true