name: Cross Trade - Frontend & Backend Bugs
description: Public test reporting, until September 13th, 2024. Report frontend & backend bugs for Cross Trade service (up to 3,300 TON reward per issue)
title: "[Cross Trade - Frontend & Backend bugs]: "
labels: ["public test: cross trade"]
assignees:
  - SonYoungsung
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Make sure you are referencing public-test/crosstrade branch.
  - type: dropdown
    id: feature
    attributes:
      label: Can you specify where the bug exists?
      multiple: true
      options:
        - Cross Trade Request UI
        - Cross Trade Provide UI
        - Cross Trade Liquidity page
        - Cross Trade history tab
        - Cross Trade Settings (fees, etc)
        - Others
        - Not sure
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? 
      placeholder: Tell us what you see! 
      value: "Describe the bug and its behavior! You can also upload the image and code links (public-test/crosstrade branch)"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-output
    attributes:
      label: Upload any screenshots to aid with explaining the bug.
      description: Upload screenshots
      placeholder:  Tell us what you see!
      value: "Upload image here"
    validations:
      required: true