name: Cross Trade - Contract Bugs
description: Contract bugs for Cross Trade service
title: "[Cross Trade - Contract Båugs]: "
labels: ["public test: cross trade"]
assignees:
  - zzooppii
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Make sure you are referencing public-test/crosstrade branch. 
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? 
      placeholder: Tell us what you see! 
      value: "Describe the bug and its behavior! You can reference the problematic code using links (public-test/crosstrade branch)"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell