import {
  MAINNET_CONTRACTS,
  SEPOLIA_CONTRACTS,
  TOKAMAK_CONTRACTS,
  TITAN_SEPOLIA_CONTRACTS,
} from "@/constant/contracts";

import { Network } from "@/staging/types/transaction";

const CONTRACTS_MAP: { [key in Network]: { [key: string]: string } } = {
  [Network.Mainnet]: {
    TON: MAINNET_CONTRACTS.TON_ADDRESS,
    WTON: MAINNET_CONTRACTS.WTON_ADDRESS,
    TOS: MAINNET_CONTRACTS.TOS_ADDRESS,
    WETH: MAINNET_CONTRACTS.WETH_ADDRESS,
    AURA: MAINNET_CONTRACTS.AURA_ADDRESS,
    LYDA: MAINNET_CONTRACTS.LYDA_ADDRESS,
    DOC: MAINNET_CONTRACTS.DOC_ADDRESS,
    USDC: MAINNET_CONTRACTS.USDC_ADDRESS,
    USDT: MAINNET_CONTRACTS.USDT_ADDRESS,
  },
  [Network.Sepolia]: {
    TON: SEPOLIA_CONTRACTS.TON_ADDRESS,
    WTON: SEPOLIA_CONTRACTS.WTON_ADDRESS,
    TOS: SEPOLIA_CONTRACTS.TOS_ADDRESS,
    WETH: SEPOLIA_CONTRACTS.WETH_ADDRESS,
    AURA: SEPOLIA_CONTRACTS.AURA_ADDRESS,
    LYDA: SEPOLIA_CONTRACTS.LYDA_ADDRESS,
    DOC: SEPOLIA_CONTRACTS.DOC_ADDRESS,
    USDC: SEPOLIA_CONTRACTS.USDC_ADDRESS,
    USDT: SEPOLIA_CONTRACTS.USDT_ADDRESS,
  },
  [Network.TitanSepolia]: {
    TON: TITAN_SEPOLIA_CONTRACTS.TON_ADDRESS,
    TOS: TITAN_SEPOLIA_CONTRACTS.TOS_ADDRESS,
    DOC: TITAN_SEPOLIA_CONTRACTS.DOC_ADDRESS,
    AURA: TITAN_SEPOLIA_CONTRACTS.AURA_ADDRESS,
    LYDA: TITAN_SEPOLIA_CONTRACTS.LYDA_ADDRESS,
    USDC: TITAN_SEPOLIA_CONTRACTS.USDC_ADDRESS,
    ETH: TITAN_SEPOLIA_CONTRACTS.OVM_ETH,
    WETH: TITAN_SEPOLIA_CONTRACTS.WETH_ADDRESS,
    USDT: TITAN_SEPOLIA_CONTRACTS.USDT_ADDRESS,
  },
  [Network.Titan]: {
    TON: TOKAMAK_CONTRACTS.TON_ADDRESS,
    TOS: TOKAMAK_CONTRACTS.TOS_ADDRESS,
    USDC: TOKAMAK_CONTRACTS.USDC_ADDRESS,
    ETH: TOKAMAK_CONTRACTS.OVM_ETH,
    WETH: TOKAMAK_CONTRACTS.WETH_ADDRESS,
    USDT: TOKAMAK_CONTRACTS.USDT_ADDRESS,
  },
};

// 함수 정의
export function getTokenAddress(network: Network, tokenSymbol: string): string {
  const contracts = CONTRACTS_MAP[network];
  return contracts ? contracts[tokenSymbol] : "";
}
