name: Vercel CI
on:
  pull_request:
    branches: ["main", "dev", "staging"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: tokamak-bridge
      APP: tokamak-bridge-webapp
      OWNER: victor
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      #INSTALL NODEJS
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      # INSTALL VERCEL CLI IN SERVER.
      - name: Install Vercel CLI
        run: npm install -g vercel
      # PULL VERCEL ENV
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ env.VERCEL_TOKEN }} --project=${{env.PROJECT}}
      # INSTALL DEPENDENCIES
      - name: Install dependencies
        run: npm install
      # BUILD
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      # TEST // To be added at some point
