name: PR Notification

on:
  pull_request:
    # types: [opened]
    branches:
      - develop
      - staging
      - production

jobs:
  PR_Open:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      APP: API-${{ github.event.pull_request.base.ref }}
      ENV: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "env": "${{ env.ENV }}",
              "app": "${{ env.APP }}",
              "pr": "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}",
              "title": "${{ github.event.pull_request.title }}"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/triggers/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
