name: PR Notification

on:
  pull_request:
    # types: [opened]
    branches:
      - dev
      - staging
      - main

jobs:
  PR_Open:
    name: A new PR opened
    runs-on: ubuntu-latest
    env:
      APP: API-${{ github.event.pull_request.base.ref }}
      ENV: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A new pull request has been opened."
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Environment*\n${{ env.ENV }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*App*\n${{ env.APP }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*PR Link*\n<${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}|PR #${{ github.event.pull_request.number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Title*\n${{ github.event.pull_request.title }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PR }}
