name: PR Notification

on:
  pull_request:
    types: [opened, reopened, closed] # Listen for both opened and closed events
    branches:
      - dev
      - staging
      - main

jobs:
  PR_Opened:
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    name: PR Opened Notification
    runs-on: ubuntu-latest
    env:
      PROJECT: BEE
      APP: tokamak-bridge-webapp
      ENV: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: Send Slack notification for opened PR
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {  
              "env": "${{ env.ENV }}",  
              "project": "${{env.PROJECT}}",
              "app": "${{ env.APP }}",  
              "pr": "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}",  
              "title": "A new PR has been opened."  
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PR }}

  PR_Merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    name: PR Merged Notification
    runs-on: ubuntu-latest
    env:
      APP: Tokamak-bridge-WebApp
      ENV: ${{ github.event.pull_request.base.ref }}

    steps:
      - name: Send Slack notification for merged PR
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {  
              "env": "${{ env.ENV }}",  
              "app": "${{ env.APP }}",  
              "pr": "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}",  
              "title": "A PR has been merged."  
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PR }}
