name: Deploy to Vercel Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "The deployment environment (e.g., development, staging, production)"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT: BEE
      APP: tokamak-bridge-webapp
      OWNER: victor
      ENV: ${{ inputs.environment }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      # INSTALL VERCEL CLI IN SERVER.
      - name: Install Vercel CLI
        run: npm install -g vercel
      # PULL VERCEL ENV
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ env.VERCEL_TOKEN }}
      # INSTALL DEPENDENCIES
      - name: Install dependencies
        run: npm install
      # Create .env file with environment variables
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_ETHEREUM_RPC=${{vars.NEXT_PUBLIC_ETHEREUM_RPC}}" > .env  
          echo "NEXT_PUBLIC_SEPOLIA_RPC=${{vars.NEXT_PUBLIC_SEPOLIA_RPC}}" >> .env
          echo "NEXT_PUBLIC_TITAN_RPC=${{vars.NEXT_PUBLIC_TITAN_RPC}}" >> .env
          echo "NEXT_PUBLIC_TITAN_SEPOLIA_RPC=${{vars.NEXT_PUBLIC_TITAN_SEPOLIA_RPC}}" >> .env
          echo "NEXT_PUBLIC_THANOS_SEPOLIA_RPC=${{vars.NEXT_PUBLIC_THANOS_SEPOLIA_RPC}}" >> .env
      # DEPLOY TO VERCEL
      - name: Deploy to Vercel
        run: vercel --prod --confirm --token=${{ secrets.VERCEL_TOKEN }} --env=${{ env.ENV}}
