name: Deploy to Vercel Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "The deployment environment (e.g., development, staging, production)"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT: BEE
      APP: tokamak-bridge-webapp
      OWNER: victor
      ENV: ${{ inputs.environment }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      #INSTALL NODEJS
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      #INSTALL VERCEL CLI IN SERVER.
      - name: Install Vercel CLI
        run: yarn global add vercel
      #PULL VERCEL ENV
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{env.ENV}} --token=${{ env.VERCEL_TOKEN }}
      #INSTALL DEPENDENCIES
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # DEPLOY TO VERCEL
      - name: Deploy to Vercel
        run: vercel --prod --confirm --token=${{ secrets.VERCEL_TOKEN }} --env=${{ env.ENV}}
