name: STAGING - Deploy on Vercel

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/shared-deploy.yaml
    with:
      environment: preview
    secrets: inherit
